---
title: "ST558 Thrid Blog Post"
author: "Shan Luo"
date: '2022-06-30'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../images/")
library(tidyverse)
library(jsonlite)
```

```{r render, echo = TRUE, eval = FALSE}
rmarkdown::render("/Users/sl666/Desktop/ST558/ShanLLL52.github.io/_Rmd/2022-06-30-ST558Blog3-post.Rmd", 
          output_format = "github_document", 
          output_dir = "/Users/sl666/Desktop/ST558/ShanLLL52.github.io/_posts",
          output_options = list(
            html_preview = FALSE))
```

I think the coolest thing is that we can use R to query data directly from internet. It is amazing that we can query data from database or APIs instead of read in file locally. I think the most interesting project that I did is the project1. I wrote my own simple function to query data from internet!  

I took my code as example:  

```{r countrysummary, echo=TRUE, eval=TRUE}
countrysummary <- function(country = "all"){
  ###
  # This function return a data.frame with COVID summary without "Premium" for all   # countries.
  ###
  
  # Get summary data from summary endpoint.
  outputAPI <- fromJSON("https://api.covid19api.com/summary")
  
  # Select only data.frame from JSON output
  output <- outputAPI$Countries
  
  # If country does not equal "all", check if it is a specific country name, code
  # or slug.
  if (country != "all"){
    
    # If country is in country name, subset output for just that row.
    if (country %in% output$Country){
      output <- output %>% 
        filter(Country == country) %>%
        select(-Premium)
    }
    # If country is in country code, subset output for just that row.
    else if (country %in% output$CountryCode){
      output <- output %>% 
        filter(CountryCode == country) %>%
        select(-Premium)
    }
    # If country is in slug, subset output for just that row.
    else if (country %in% output$Slug){
      output <- output %>% 
        filter(Slug == country) %>%
        select(-Premium)
    }
    # Otherwise, throw an information error.
    else{
      message <- paste("ERROR: Argument for country was not found in",
                       "the Country, CountryCode, or Slug columns. Try",
                       "countrysummary('all') to find the country you're",
                       "looking for.")
      stop(message)
    }
  }
  # Do nothing if country value equals "all".
  else{
    
  } 
  # Return the output data.frame.
  return(output)
}
```

```{r test func, echo=TRUE, eval=TRUE}
as_tibble(countrysummary('china'))
```

It returns COVID case information about China.  